local levelData = { 
  'Level 1',
  { '', 'Meteor:1', '' },
  { 'Meteor:1', '', 'Meteor' },
  { '', 'Meteor:1', '' },
  { 'Meteor:1', '', 'Meteor' },
  { 'Upgrade' },
  { 'Alpha', '', 'Alpha' },
  { '', 'Alpha', '' },
  { 'Alpha', '', 'Alpha' },
  { 'Meteor:2', '', '' },
  { '', 'Meteor:2', '' },
  { '', '', 'Meteor:2' },
  { 'Meteor:2', '', '' },
  { '', 'Meteor:2', '' },
  { '', '', 'Meteor:2' },
  { 'Upgrade' },
  { 'Alpha' },
  { 'Meteor:3', 'Meteor:3' },
  { 'Meteor:3' },
  { 'Meteor:3', 'Meteor:3' },
  { 'Meteor:3', 'Meteor:3', 'Meteor:3' },
  { 'Meteor:3', 'Meteor:3' },
  { 'Meteor:3', 'Meteor:3', 'Meteor:3' },
  { 'Bravo' },
  { 'Bravo', 'Bravo' },
  { 'Bravo', 'Bravo', 'Bravo' },
  { 'Bravo', '', 'Bravo', '' },
  { '', 'Bravo', '', 'Alpha' },
  { 'Alpha', '', 'Bravo', '' },
  { '', 'Bravo', '', 'Alpha' },
  { 'Upgrade' },
  { 'Charlie', '' },
  { '', 'Charlie' },
  { 'Charlie', '' },
  { '', 'Charlie' },
  { 'Meteor:4', '', '' },
  { '', '', 'Meteor:4' },
  { 'Meteor:4' },
  { 'Upgrade', '', '' },
  { 'Boss1' },
}
return levelData